spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.126.22:2181
  protocol:
    port: 20881
  consumer:
    check: false
server:
  port: 8080
