spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.126.129:2181
  consumer:
    check: false

server:
  port: 8080

tracker:
  port: 192.168.126.4

fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 160
    height: 130
  tracker-list:
    - ${tracker.port}:22122
