server:
  port: 8085
spring:
  redis:
    host: 192.168.126.129
    password: root
dubbo:
  registry:
    address: zookeeper://192.168.126.129:2181
  consumer:
    check: false
  application:
    name: shop_cart
