server:
  port: 8083
dubbo:
  application:
    name: shop_item
  registry:
    address: zookeeper://192.168.126.129:2181
  consumer:
    check: false
spring:
  rabbitmq:
    host: 192.168.126.4
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672