
dubbo:
  registry:
    address: zookeeper://192.168.126.129:2181
  protocol:
    port: 20883
  application:
    name: shop_service_cart
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.126.129
    password: root
server:
  port: 9095

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml